[project]
name = "rideshare-pilots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = ["Addison Hanrattie"]
requires-python = ">=3.14"
dependencies = [
    "minigrid>=3.0.0",
]
